<?php $this->layout('layout::default', ['title' => 'Home', 'usuario' => null, 'baseUrl' => $baseUrl]) ?>

<div class="row justify-content-center">
	<div class="col-md-6">
<?php if (isset($error)): ?>
		<div class="card text-white bg-danger mb-3">
			<div class="card-header">Erro</div>
			<div class="card-body">
				<?= $this->e($error) ?>
			</div>
		</div>
<?php endif; ?>
		<div class="card card-default">
			<div class="card-header card-header-tabs">
				<ul class="nav nav-tabs" role="tablist">
					<li role="presentation" class="nav-item">
						<a href="#form-login" class="nav-link<?= empty($tabRegister) ? ' active' : '' ?>" aria-controls="form-login" role="tab" data-toggle="tab">Login</a>
					</li>
					<li role="presentation" class="nav-item">
						<a href="#form-register" class="nav-link<?= isset($tabRegister) ? ' active' : '' ?>" aria-controls="form-register" role="tab" data-toggle="tab">Cadastrar</a>
					</li>
				</ul>
			</div>
			<div class="card-body tab-content">
				<div class="tab-pane<?= empty($tabRegister) ? ' active' : '' ?>" role="tabcard" id="form-login">
					<form class="form-horizontal" action="<?= $baseUrl ?>/login" method="post">
						<div class="form-group row">
							<label class="col-md-2 col-form-label">E-mail</label>
							<div class="col-md-10">
								<input type="text" class="form-control" name="username" value="<?= isset($username) ? $this->e($username) : '' ?>"/>
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-2 col-form-label">Senha</label>
							<div class="col-md-10">
								<input type="password" class="form-control" name="password"/>
							</div>
						</div>
						<div class="form-group row mb-0">
							<label class="col-md-2 col-form-label"></label>
							<div class="col-md-10">
								<button type="submit" class="btn btn-primary">Entrar</button>
							</div>
						</div>
					</form>
				</div>
				<div class="tab-pane<?= isset($tabRegister) ? ' active' : '' ?>" role="tabcard" id="form-register">
<?php if (!empty($register_success)): ?>
					<div class="alert alert-success" role="alert">
						<p><strong>Cadastro realizado com sucesso!</strong></p>
					</div>
					<p>O administrador irá verificar seus dados e realizar a liberação de acesso.</p>
					<p>Você receberá um aviso por e-mail quando isso acontecer.</p>
<?php else: ?>
					<form class="form-horizontal" action="<?= $baseUrl ?>/usuario/cadastrar" method="post">
						<div class="form-group row">
							<label class="col-md-4 col-form-label">Nome</label>
							<div class="col-md-8">
								<input type="text" class="form-control" name="name" value="<?= isset($register_name) ? $this->e($register_name) : '' ?>"/>
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-4 col-form-label">E-mail</label>
							<div class="col-md-8">
								<input type="text" class="form-control" name="email" value="<?= isset($register_email) ? $this->e($register_email) : '' ?>"/>
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-4 col-form-label">Senha</label>
							<div class="col-md-8">
								<input type="password" class="form-control" name="password" value="<?= isset($register_password) ? $this->e($register_password) : '' ?>"/>
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-4 col-form-label">Confirme a senha</label>
							<div class="col-md-8">
								<input type="password" class="form-control" name="password_confirm"/>
							</div>
						</div>
						<div class="form-group row mb-0">
<?php if (isset($register_error)): ?>
							<div class="alert alert-danger" role="alert">
								<p><?= $this->e($register_error) ?></p>
							</div>
<?php endif; ?>
							<label class="col-md-4 col-form-label"></label>
							<div class="col-md-8">
								<button type="submit" class="btn btn-primary">Enviar</button>
							</div>
						</div>
					</form>
<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
</div>
