<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title><?=$this->e($title)?> - zend-expressive</title>
    <link rel="shortcut icon" href="https://framework.zend.com/ico/favicon.ico" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous" />

    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet" />
    <style>
        body { padding-top: 70px; }
        .app { min-height: 100vh; }
        .app-footer { padding-bottom: 1em; }
        .zf-green, h2 a { color: #68b604; }
        .card-header-tabs {
            margin: 0;
            padding: 0;
        }
        .card-header-tabs .nav-tabs {
            margin: 0 0 -1px;
            padding: .75rem .75rem 0;
        }
    </style>
    <?=$this->section('stylesheets')?>
</head>
<body class="app">
    <header class="app-header">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Brand -->
                    <a class="navbar-brand" href="/">
                        <img src="https://framework.zend.com/images/logos/zf-logo-mark.png" alt="Zend Expressive" height="28" />
                    </a>
                </div>
                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a href="https://docs.zendframework.com/zend-expressive" target="_blank" class="nav-link">
                                <i class="fa fa-book"></i> Docs
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="https://github.com/zendframework/zend-expressive" target="_blank" class="nav-link">
                                <i class="fa fa-wrench"></i> Contribute
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/api/ping" class="nav-link">
                                Ping Test
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container">

            <div class="row">
                <div class="col-md-3">
                    <div class="list-group">
                        <a class="list-group-item" href="<?= $baseUrl ?>/">Home</a>
<?php if (empty($usuario)): ?>
                        <a class="list-group-item" href="<?= $baseUrl ?>/login">Login</a>
                        <a class="list-group-item" href="<?= $baseUrl ?>/usuario/cadastrar">Cadastrar usuário</a>
<?php else: ?>
                        <span class="list-group-item"><?= $this->e($usuario->usuario_nome) ?></span>
                        <a class="list-group-item" href="<?= $baseUrl ?>/logout">Logout</a>
<?php endif; ?>
                    </div>
                </div>
            </div>

            <?=$this->section('content')?>
        </main>
    </div>

    <footer class="app-footer">
        <div class="container">
            <hr />
            <?php if ($this->section('footer')): ?>
                <?=$this->section('footer')?>
            <?php else: ?>
                <p>
                    &copy; 2005 - <?=date('Y')?> by Zend Technologies Ltd. All rights reserved.
                </p>
            <?php endif ?>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <?=$this->section('javascript')?>
</body>
</html>
